Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: WeatherSampleLambda::WeatherSampleLambda.Function::FunctionHandler
      CodeUri: C:\Git\dotnet-on-AWS-examples\WeatherSampleLambda\src\WeatherSampleLambda
      Runtime: dotnet6
      Architectures:
        - x86_64